api-service:
  url: http://api-service
core-service:
  url: http://core-service
mp-import-service:
  url: http://localhost:12120/MPImport


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8767

feign:
  client:
    config:
      default:
        connectTimeout: 5000   # Thời gian chờ kết nối (ms)
        readTimeout: 5000      # Thời gian chờ đọc dữ liệu (ms)
        loggerLevel: FULL      # Log chi tiết request & response

spring:
  servlet:
    # Giới hạn kích thước file tải lên
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      # Giới hạn tổng số lượng file tải lên
      file-size-threshold: 2MB

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=PRODUCTION;encrypt=false;trustServerCertificate=true;
    username: sa
    password: dev*2304
  data:
    mongodb:
      uri: mongodb://localhost:27017/AlvaDB
      
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0  # Thu thập 100% trace (có thể giảm xuống 0.1 nếu quá tải)

swagger:
  enabled: true

logging:
  level:
    org.springframework: ERROR