eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=DATA_PROSHOP;encrypt=false;trustServerCertificate=true;
    username: sa
    password: dev*2304
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0  # Thu thập 100% trace (có thể giảm xuống 0.1 nếu quá tải)

server:
  port: 8777
swagger:
  enabled: true
