eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=PRODUCTION;encrypt=false;trustServerCertificate=true;
    username: sa
    password: dev*2304
  data:
    mongodb:
      uri: mongodb://localhost:27017/AlvaDB

  zipkin:
    base-url: http://zipkin-server:9411
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0  # Thu thập 100% trace (có thể giảm xuống 0.1 nếu quá tải)