eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8764

spring:
  aop:
    auto: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=PRODUCTION;encrypt=false;trustServerCertificate=true;
    username: sa
    password: dev*2304
  servlet:
    # Giới hạn kích thước file tải lên
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      # Giới hạn tổng số lượng file tải lên
      file-size-threshold: 2MB

  zipkin:
    base-url: http://zipkin-server:9411
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0  # Thu thập 100% trace (có thể giảm xuống 0.1 nếu quá tải)

swagger:
  enabled: true

logging:
  level:
    org.springframework: ERROR
token:
  time:
    refresh: 84000000